from settings import *

AWS_ACCESS_KEY = '...'
AWS_ACCESS_SECRET = '...'
AWS_STORAGE_BUCKET_NAME = '...'
AWS_CLOUDFRONT_ORIGIN_NAME = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_CLOUDFRONT_DISTRIBUTION_COMMENT = "XXXX XXX"

DJANGO_STATIC = True
DJANGO_STATIC_SAVE_PREFIX = '/tmp/infinity_static_files/kl'
DJANGO_STATIC_NAME_PREFIX = '/cache-forever'

DJANGO_STATIC_FILE_PROXY = 'cloudfront.file_proxy'
